.TH "efc::Token" 3 "Wed Mar 1 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
efc::Token \- Struct for representing a token as a type and a value\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBTokenType\fP \fBtype\fP"
.br
.RI "The token's type as a TokenType\&. "
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char \fBc\fP"
.br
.ti -1c
.RI "   int \fBn\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.RI "A union representing the value of the \fBToken\fP as a char or as a int\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for representing a token as a type and a value\&. 
.PP
Definition at line \fB674\fP of file \fBinterface\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char efc::Token::c"

.PP
Definition at line \fB682\fP of file \fBinterface\&.cpp\fP\&.
.SS "int efc::Token::n"

.PP
Definition at line \fB682\fP of file \fBinterface\&.cpp\fP\&.
.SS "const \fBTokenType\fP efc::Token::type"

.PP
The token's type as a TokenType\&. 
.PP
Definition at line \fB678\fP of file \fBinterface\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
