.TH "efc::Plane" 3 "Sun Mar 19 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
efc::Plane \- \fBPlane\fP class to draw a function in the Cartesian plane\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlane\fP (int ox, int oy, const \fB::emth::Polynomial\fP &func)"
.br
.RI "The main constructor\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "Runs the main application loop, processing events\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBPlane\fP class to draw a function in the Cartesian plane\&. 

Provides the capability to run multiple Planes in different threads in paralell 
.PP
Definition at line \fB452\fP of file \fBinterface\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "efc::Plane::Plane (int ox, int oy, const \fB::emth::Polynomial\fP & func)\fC [inline]\fP"

.PP
The main constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIox\fP The x offset 
.br
\fIoy\fP The y offset 
.br
\fIfunc\fP The function to be drawed 
.RE
.PP

.PP
Definition at line \fB547\fP of file \fBinterface\&.cpp\fP\&.
.PP
References \fBROBOTO_BOLD\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void efc::Plane::run ()\fC [inline]\fP"

.PP
Runs the main application loop, processing events\&. 
.PP
Definition at line \fB558\fP of file \fBinterface\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
