.TH "test/emath.cpp" 3 "Sat Feb 11 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/emath.cpp \- This is the main test file of the emath library\&. It contains all the tests needed to assure that the library works properly\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'emath\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtest_monomial\fP ()"
.br
.RI "Runs all the monomial class tests\&. "
.ti -1c
.RI "int \fBtest_polynomial\fP ()"
.br
.RI "Runs all the polynomial class tests\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Calls the monomial and polynomial tests\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the main test file of the emath library\&. It contains all the tests needed to assure that the library works properly\&. 

This file contains a main function that calls a function for the monomials and a function for the polynomials that test that every method works as it should\&.
.br
If it doesn't then a message gets printed to the console describing the error\&. If this does happen open an issue on my github page\&. 
.PP
Definition in file \fBemath\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Calls the monomial and polynomial tests\&. 
.PP
\fBReturns\fP
.RS 4
(int) The sum of the test_monomial and test_polynomial function wich should be zero when all tests pass 
.RE
.PP

.PP
Definition at line \fB206\fP of file \fBemath\&.cpp\fP\&.
.PP
References \fBtest_monomial()\fP, and \fBtest_polynomial()\fP\&.
.SS "int test_monomial ()"

.PP
Runs all the monomial class tests\&. 
.PP
\fBReturns\fP
.RS 4
(int) Returns 0 to specify to Meson that the tests finished correctly 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBemath\&.cpp\fP\&.
.PP
References \fBemth::Monomial::get_coeff()\fP, \fBemth::Monomial::get_degree()\fP, \fBemth::Monomial::get_expression()\fP, and \fBemth::Monomial::get_value()\fP\&.
.SS "int test_polynomial ()"

.PP
Runs all the polynomial class tests\&. 
.PP
\fBReturns\fP
.RS 4
(int) Returns 0 to specify to Meson that the tests finished correctly 
.RE
.PP

.PP
Definition at line \fB102\fP of file \fBemath\&.cpp\fP\&.
.PP
References \fBemth::Polynomial::get_degree()\fP, \fBemth::Polynomial::get_derivative()\fP, \fBemth::Polynomial::get_expression()\fP, \fBemth::Polynomial::get_integral()\fP, \fBemth::Polynomial::get_monomials()\fP, and \fBemth::Polynomial::get_value()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
