.TH "emth::Arithmetic" 3 "Wed Mar 1 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emth::Arithmetic \- Class with some functions for arithmetic math\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <emath\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBget_divisors\fP (int n, std::vector< int > &v) noexcept"
.br
.RI "Gets the all the positive divisors for an integer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class with some functions for arithmetic math\&. 

The class consists of the functions that operate with real numbers\&. 
.PP
Definition at line \fB173\fP of file \fBemath\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void emth::Arithmetic::get_divisors (int n, std::vector< int > & v)\fC [static]\fP, \fC [noexcept]\fP"

.PP
Gets the all the positive divisors for an integer\&. 
.PP
\fBParameters\fP
.RS 4
\fIn\fP The integer to get the divisors for\&. 
.br
\fIv\fP The vector reference where to store the divisors\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBemath\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
