.TH "emthp::Token" 3 "Mon Feb 27 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emthp::Token \- Struct for representing a token as a type and a value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eparser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTokenType\fP \fBtype\fP"
.br
.RI "The token's type as a TokenType\&. "
.ti -1c
.RI "double \fBvalue\fP"
.br
.RI "The token's numerical value as a double\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for representing a token as a type and a value\&. 
.PP
Definition at line \fB54\fP of file \fBeparser\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTokenType\fP emthp::Token::type"

.PP
The token's type as a TokenType\&. 
.PP
Definition at line \fB59\fP of file \fBeparser\&.h\fP\&.
.SS "double emthp::Token::value"

.PP
The token's numerical value as a double\&. 
.PP
Definition at line \fB63\fP of file \fBeparser\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
