.TH "emth" 3 "Sat Feb 11 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emth \- Englobes all the classes and functions of the emath library\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArithmetic\fP"
.br
.RI "Class with some functions for arithmetic math\&. "
.ti -1c
.RI "class \fBMonomial\fP"
.br
.RI "Class for representing and operating monomials\&. "
.ti -1c
.RI "class \fBPolynomial\fP"
.br
.RI "Class for representing and operating polynomials\&. "
.in -1c
.SH "Detailed Description"
.PP 
Englobes all the classes and functions of the emath library\&. 

The emth namespace contains three classes: \fBArithmetic\fP, \fBMonomial\fP and \fBPolynomial\fP\&. The first contains functions for arithmetic operations\&. The last two are wrappers on abstract algebraic concepts\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
