.TH "emthp" 3 "Mon Feb 27 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emthp \- Englobes all the classes and functions of the parser\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLexer\fP"
.br
.RI "Class that works as a token supplier for the \fBParser\fP class\&. "
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "Class that wraps a std::string and parses it as a Monomial or as a Polynomial\&. "
.ti -1c
.RI "struct \fBToken\fP"
.br
.RI "Struct for representing a token as a type and a value\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTokenType\fP { \fBT_PLUS\fP, \fBT_MINUS\fP, \fBT_NUMBER\fP, \fBT_VARIABLE\fP, \fBT_EXPONENT\fP, \fBT_EOF\fP }"
.br
.RI "Enum with all the possible Token types\&. "
.in -1c
.SH "Detailed Description"
.PP 
Englobes all the classes and functions of the parser\&. 

The emthp namespace contains two classes: \fBParser\fP and \fBLexer\fP\&. It also contains the TokenType enum and a \fBToken\fP struct\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBemthp::TokenType\fP"

.PP
Enum with all the possible \fBToken\fP types\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIT_PLUS \fP\fP
Plus sign type\&. 
.TP
\fB\fIT_MINUS \fP\fP
Minus sign type\&. 
.TP
\fB\fIT_NUMBER \fP\fP
Number type\&. 
.TP
\fB\fIT_VARIABLE \fP\fP
X type\&. 
.TP
\fB\fIT_EXPONENT \fP\fP
Exponent sign type\&. 
.TP
\fB\fIT_EOF \fP\fP
EOF type\&. 
.PP
Definition at line \fB24\fP of file \fBeparser\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
