.TH "include/eparser.h" 3 "Sat Feb 11 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/eparser.h \- This is the main header file for the equation parser\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'emath\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBemthp::Token\fP"
.br
.RI "Struct for representing a token as a type and a value\&. "
.ti -1c
.RI "class \fBemthp::Lexer\fP"
.br
.RI "Class that works as a token supplier for the \fBParser\fP class\&. "
.ti -1c
.RI "class \fBemthp::Parser\fP"
.br
.RI "Class that wraps a std::string and parses it as a Monomial or as a Polynomial\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBemthp\fP"
.br
.RI "Englobes all the classes and functions of the parser\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBemthp::TokenType\fP { \fBemthp::T_PLUS\fP, \fBT_MINUS\fP, \fBT_NUMBER\fP, \fBT_VARIABLE\fP, \fBT_EXPONENT\fP, \fBT_EOF\fP }"
.br
.RI "Enum with all the possible Token types\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the main header file for the equation parser\&. 

This file contains the classes and functions for parsing polynomials and monomials\&.
.br
It consists of two classes, the Parser class and the Lexer class\&.
.br
The Parser class consists of two functions, one for parsing the entire input as a Polynomial and another for parsing a Monomial at a time\&.
.br
The Lexer class just provides a token supplier for the Parser class\&.
.br

.PP
Definition in file \fBeparser\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
