.TH "src/font.h" 3 "Sun Mar 19 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/font.h \- This file contains some fonts as a unsigned char arrays\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned char \fBROBOTO_BOLD\fP []"
.br
.RI "The Roboto Bold font as a unsigned char array\&. "
.ti -1c
.RI "unsigned int \fBROBOTO_BOLD_SIZE\fP = 167336"
.br
.RI "The Roboto Bold font size as a unsigned int\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains some fonts as a unsigned char arrays\&. 

This file was written using the xxd utility 
.PP
Definition in file \fBfont\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned char ROBOTO_BOLD[]"

.PP
The Roboto Bold font as a unsigned char array\&. 
.PP
Definition at line \fB12\fP of file \fBfont\&.h\fP\&.
.SS "unsigned int ROBOTO_BOLD_SIZE = 167336"

.PP
The Roboto Bold font size as a unsigned int\&. 
.PP
Definition at line \fB13962\fP of file \fBfont\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
