.TH "test" 3 "Tue Feb 28 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Testing 
.PP

.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Lexer)\fP" 1c
Test lexer functionality with simple expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, CompoundLexer)\fP" 1c
Test lexer functionality with compund expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, ArithmeticLexer)\fP" 1c
Test lexer functionality with arithmetic expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Variables)\fP" 1c
Test parser functionality with monomial expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Compound)\fP" 1c
Test parser functionality with polynomial expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Signs)\fP" 1c
Test parser functionality with sign expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Noise)\fP" 1c
Test parser functionality with noise in the expressions  
.IP "\fBMember \fBTEST_F\fP (\fBEParserTest\fP, Edge)\fP" 1c
Test parser edge cases 
.PP

