.TH "value" 3 "Mon Feb 27 2023" "EMath++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
value \- A union representing the value of the Token as a char or as a int\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A union representing the value of the Token as a char or as a int\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EMath++ from the source code\&.
